# place api here
---
NEWS_API:
- News: "f3c1acee07784d5394185efbe449bba0"
FARMER_API:
- Farmer: "7DK7A25B47JGHFE8G41BE83K77C84D"
LINEBOT_NOTIFY_API:
- Gift-List(test1): "E1yA08X9sWrqNPaeTk404s748a1mbae2ODS1b7thmmi"
GOOGLE_MAP:
- Place_api: "AIzaSyDn1SNO-unHl8mSu2u3ZQ7dzfab4Y5bOZ0"
CAFE_NOMAD:
- Cafe_api: 'https://cafenomad.tw/api/v1.2/cafes'
